### ISSUE TITLE
Tab Feature in the Component Generator

### ISSUE THREAD

**Issue by sudheerdvn** [adobe/aem-component-generator#30]
I was trying to use the aem-component-generator and able to successfully generate dialog and sling models. 

First of all, it is a great feature which makes our regular work easy to start on creating any new component. Thank you for making it available.

Most of the times, we have to create multiple tabs in the components, Do we have any options already available to create tabs in the dialog?

I have modified the code a little bit in my local and able to create the multiple tabs in the dialog and able to pull the same properties in sling model. but that is still in draft and might need to cover more test cases and finalize the approach. Would like to check if the feature is already planned and some one is working on it.

**Comment by HitmanInWis** [comment]
@sudheerdvn thanks for asking.  The ability to have tabs on the dialog is a feature that has been requested by a few folks, but I know of no one that is actively working on adding the feature.  I encourage you to create a pull request so that it can be reviewed.

Very excited to see this feature coming!

**Comment by HitmanInWis** [comment]
This is resolved by https://github.com/adobe/aem-component-generator/pull/31
